### ISSUE TITLE
Открыть доступ к репозиторию для исправления

### ISSUE THREAD

**Issue by as-evseenko** [alezhu/otp_direkt_mcc#4]
Александр, привет!
У меня категория карты "Рестораны и развлечения", и я сделал небольшие правки описаний MCC кодов и названия самой категории (в direkt'e оно обрезано, поэтому не работает по умолчанию). И хотел бы залить свои правки, но доступа нет.
Можешь открыть доступ на создание веток?

Могу залить через пул-реквест.
Либо открыть всем заливку в master - без прав на force push, потом если вдруг что - сможешь откатить (хотя этот вариант рискованней, всё-таки это js-скрипт, кто-то может на время встроить что угодно в него).

https://www.banki.ru/blog/alezhu/10184.php
![image](https://user-images.githubusercontent.com/34393515/55672013-bec26a00-589e-11e9-881e-0af8ce78326b.png)

**Comment by alezhu** [comment]
Присылай PR

**Comment by as-evseenko** [comment]
> Присылай PR

В том-то и дело, нет возможности создать PR пока закрыта возможность запушить свою ветку :) можно через форк, но только если по-другому никак (разрешить создать ветку), то сделаю, конечно через форк..

**Comment by alezhu** [comment]
Ну так и делают. Делаешь форк, правишь свой форк, присылаешь PR

**Comment by as-evseenko** [comment]
> Ну так и делают. Делаешь форк, правишь свой форк, присылаешь PR

Окей, сделаю, с форком бредовая конечно штука, как мне кажется, тяжелее синхронизировать нормально, кажется, должна быть возможность настроить права на один репозиторий, чтобы не пушить в основную ветку, но ок, форком значит форком

**Comment by alezhu** [comment]
Ну это если вести командную разработку, то наверное. Я не разбирался с этим. А тут я даже никаких веток кроме мастера не завожу. 
Спасибо за исправления.

**Comment by as-evseenko** [comment]
> Ну это если вести командную разработку, то наверное. Я не разбирался с этим. А тут я даже никаких веток кроме мастера не завожу.
> Спасибо за исправления.

Да, супер! Если что - я на связи (и с категорией Рестораны и развлечения :) )
